application:
  name: mams-csp-imgEngine
image:
  libraryPath: E:/Users/admin/IdeaProjects/new/licy/gongsi2/mams-csp-imgEngine/src/main/resources/opencv/x64/opencv_java341.dll
#  libraryPath: /usr/lib64/libopencv_java341.so
#  blackLogoFile: C:/Users/49468/Desktop/shiliangtu/logo/logoopen.png
#  blackLogoFile: C:/Users/49468/Desktop/shiliangtu/logo/logoopen.jpg
#  blackLogoFile: /opt/logo/logoBlack.png
#  blackLogoFile[0]: /opt/yanhua-erp-consumer-engine/logo/logoBlack.png
#  blackLogoFiles[0]: C:/Users/49468/Desktop/shiliangtu/logo/logoo1.png
#  blackLogoFiles[1]: C:/Users/49468/Desktop/shiliangtu/logo/huilogo.png
#  blackLogoFiles[2]: C:/Users/49468/Desktop/shiliangtu/logo/2013.bmp
  logoPropertiesList:
    -
      blackLogoFile: C:/Users/49468/Desktop/shiliangtu/logo/logoo1.png
      whiteLogoFile: C:/Users/49468/Desktop/shiliangtu/logo/logoo2.png
      watermarkWidth: 50
      watermarkHeight: 17
    -
      blackLogoFile: C:/Users/49468/Desktop/shiliangtu/logo/bailogo.png
      whiteLogoFile: C:/Users/49468/Desktop/shiliangtu/logo/huilogo.png
      watermarkWidth: 50
      watermarkHeight: 17
    -
      blackLogoFile: C:/Users/49468/Desktop/shiliangtu/logo/2013.bmp
      whiteLogoFile: C:/Users/49468/Desktop/shiliangtu/logo/2013.bmp
      watermarkWidth: 50
      watermarkHeight: 17
#  logo[1]:
#    blackLogoFiles: C:/Users/49468/Desktop/shiliangtu/logo/huilogo.png
#    whiteLogoFiles: C:/Users/49468/Desktop/shiliangtu/logo/huilogo.png
#    watermarkWidth: 50
#    watermarkHeight: 17
#  logo[2]:
#    blackLogoFiles: C:/Users/49468/Desktop/shiliangtu/logo/2013.bmp
#    whiteLogoFiles: C:/Users/49468/Desktop/shiliangtu/logo/2013.bmp
#    watermarkWidth: 50
#    watermarkHeight: 17
  useGraphics: true
  graphicsMagickPath: G://Program Files//GraphicsMagick-1.3.35-Q8
  imageMagickPath: G://Program Files//ImageMagick-7.0.10-Q16
  useWindows: true
#imageMagickPath
#magick:
#  useGraphics: true
#  graphicsMagick:
#    path: G://Program Files//GraphicsMagick-1.3.35-Q8
#  imageMagick:
#    path: G://Program Files//ImageMagick-7.0.10-Q16